# Generated by Django 2.2.3 on 2019-07-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='models',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
