# Generated by Django 2.2.3 on 2019-07-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_post_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='models',
        ),
        migrations.AddField(
            model_name='user',
            name='models',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
